### ISSUE TITLE
'Today' button does not appear when a site is open where the loan is being generate from

### ISSUE THREAD

**Issue by LESupport** [lend-engine/lend-engine-app#130]
As admin used the "Today" button in the calendar does not appear when there is a valid today time in the calendar is available. Site-specific opening times need to be taken into account and need to determine which site to use as default or different conditions to allow the button.

**Comment by andortamas** [comment]
Today button is an admin only feature, so we allowed for some flexibility. This bug causes in some complex circumstances, so fixing this would be complex.

Now the today button is available if the item's site id is opened today, otherwise I hide it. The choose date button works fine (if you would like to pick up from another location), so it doesn't cause an issue.
