### ISSUE TITLE
Email wording changes

### ISSUE THREAD

**Issue by andortamas** [lend-engine/lend-engine-app#187]

**Comment by andortamas** [comment]
Changes the wording on /admin/settings/templates and related email from 'Your loan is due tomorrow' to 'Pick up your reservation %loanId% soon'

**Comment by andortamas** [comment]
Deployed

**Comment by LESupport** [comment]
Loan Return emails Subject: reads "Pick up your reservation %2210% soon" this should be "your loan 2210 is due back soon."

Also, the % sign should not be there in the email, and the "soon" is important as some think it's due back immediately

In the section relating to email templates the following needs updating:-

Loan reminder
Sent the day before a loan is due to be returned.

Needs updating to 
Loan reminder
Sent x day(s) before a loan is due to be returned. (configure in General Settings)

Reservation reminder
Sent the day before a reservation is due to be picked up.

Needs updating to
Reservation reminder
Sent x day(s) before a reservation is due to be picked up. (configure in General Settings)

![dueback](https://user-images.githubusercontent.com/76882506/168286385-7f38f04a-92a1-464c-a5de-594cb74f49d8.jpg)
